Stop throwing exceptions if getting an image causes an error.
 o This seems to happen pretty often, and throwing an exception
   just seems cruel. Instead we will just ignore that frame.

 o For the record, this is the error I'm talking about:

ERROR: There is an image consistency issue with this image.
SUpport info: Error Trace:
Source: CameraInternal.cpp(123) Built: Oct  4 2012 04:38:07 - There is
an image consistency issue with this image.
+-> From: Iso.cpp(759) Built: Oct  4 2012 04:38:19 - There is an image
consistency issue with this image.